version: "3.8"

services:
  devtools:
    build:
      dockerfile: devtools.Dockerfile
      target: cv
      cache_from:
        - type=gha
    volumes:
      - .:/srv/src:z
    working_dir: /srv/src
  docker-lock:
    image: docker.io/safewaters/docker-lock:latest@sha256:432d90ddc2891f4845241adc63e5eef2dd1486fa14ea7882433cbd3f8ed64622
    volumes:
      - .:/srv/src
    working_dir: /srv/src
