on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: ">=0.8 <1.0"
      - run: |
          earthly +ci
      - if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create $(date '+%Y%m%d%H%M%S') --generate-notes --latest barskov-nikita-cv.pdf
